# Generated by Django 4.1 on 2022-08-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='handler',
        ),
        migrations.AddField(
            model_name='complaint',
            name='handler',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
