# Generated by Django 4.1 on 2022-08-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_complaint_handler_complaint_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='handler',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
