# Generated by Django 4.1 on 2022-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_complaint_comment_ticketid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='handler',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
