# Generated by Django 4.1 on 2022-08-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_progressbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressbar',
            name='body',
            field=models.TextField(max_length=3, null=True),
        ),
    ]
