# Generated by Django 4.1 on 2022-08-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_progressbar_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressbar',
            name='body',
            field=models.TextField(blank=True, max_length=3, null=True),
        ),
    ]
