# Generated by Django 4.1 on 2022-08-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_progressbar_commenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressbar',
            name='body',
        ),
        migrations.AddField(
            model_name='progressbar',
            name='bodyy',
            field=models.TextField(max_length=3, null=True),
        ),
    ]
