# Generated by Django 4.1 on 2022-08-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_progressbar_body_progressbar_bodyy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
