# Generated by Django 4.1 on 2022-08-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressbar',
            old_name='bodyy',
            new_name='body',
        ),
    ]
