# Generated by Django 4.1 on 2022-08-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_bodyy_progressbar_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressbar',
            old_name='body',
            new_name='bar',
        ),
        migrations.RenameField(
            model_name='progressbar',
            old_name='commenter',
            new_name='commentee',
        ),
        migrations.RenameField(
            model_name='progressbar',
            old_name='ticketid',
            new_name='tid',
        ),
    ]
